# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yash Diniz 
subtitle: Contributing to history way too often.
email: y@yashdiniz.me
description: Yash Diniz, speaking mostly about software and systems architecture, along with everything else.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yashdiniz.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yashdiniz
github_username: yashdiniz

title_image: "/assets/img/logo512.png"

paginate: 5
paginate_path: "/blog/page:num"
permalink: "/blog/:title/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  # toc_levels: 1..3

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - CNAME
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

